fix infinite loop
zendframework/zend-mime pull request #32
Opened 2018-02-08 13:41 UTC by EugenGanshorn

If a message contains 72 spaces and 72 dots at one line we have an infinite loop. This pull request fix this behavior.
I'll replace the last space at one line always with =20. I'll also replace the first dot at one line always with =2E.
Swiftmail do it the same way and it works fine.

2018-02-21 15:15 UTC, nicolashohm requested changes

2018-02-21 15:15 UTC, nickel715 commented on src/Mime.php
> +            switch (ord($str[0])) {
maybe an if instead of a switch?

2018-02-21 15:15 UTC, nickel715 commented on src/Mime.php
> +                case 0x2E:
would be easier to read if you add an comment with the translation of the hex code

2018-02-21 15:15 UTC, nickel715 commented on src/Mime.php
> +            switch (ord(substr($str, $ptr - 1))) {
you got these code from somethere else? please add a link in comments or commit message

2018-03-13 14:39 UTC, Rfrost92 approved these changes

2018-03-13 14:40 UTC, Rfrost92 approved these changes
Tested these changes in our mail system, everything seems to work fine. The bug is fixed

2018-03-26 13:15 UTC, usox approved these changes

2018-05-14 19:03 UTC, merged

2018-05-14 19:03 UTC, weierophinney commented
Thanks, @EugenGanshorn.